"""
Content Classifier - Quality Assessment Models

This module provides quality assessment models for document classification.
The actual classification is performed by DynamicSemanticClassifier using LLM.

Note: TaxCategory enum and keyword-based classification have been removed.
Use DynamicSemanticClassifier for all classification needs.
"""

import logging
from typing import List, Optional

from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)


class QualityMetrics(BaseModel):
    """Five-dimensional quality assessment metrics."""

    completeness: float = Field(default=0.0, ge=0.0, le=1.0, description="Content completeness score")
    accuracy: float = Field(default=0.0, ge=0.0, le=1.0, description="Information accuracy score")
    relevance: float = Field(default=0.0, ge=0.0, le=1.0, description="Topic relevance score")
    clarity: float = Field(default=0.0, ge=0.0, le=1.0, description="Expression clarity score")
    practicality: float = Field(default=0.0, ge=0.0, le=1.0, description="Practical usefulness score")

    @property
    def overall_score(self) -> float:
        """Calculate weighted average quality score."""
        weights = {
            "completeness": 0.25,
            "accuracy": 0.25,
            "relevance": 0.20,
            "clarity": 0.15,
            "practicality": 0.15
        }
        return (
            self.completeness * weights["completeness"]
            + self.accuracy * weights["accuracy"]
            + self.relevance * weights["relevance"]
            + self.clarity * weights["clarity"]
            + self.practicality * weights["practicality"]
        )

    @property
    def quality_grade(self) -> str:
        """Convert overall score to letter grade."""
        score = self.overall_score
        if score >= 0.9:
            return "A+"
        elif score >= 0.8:
            return "A"
        elif score >= 0.7:
            return "B"
        elif score >= 0.6:
            return "C"
        elif score >= 0.5:
            return "D"
        else:
            return "F"


class ClassificationResult(BaseModel):
    """Document classification result.

    Note: primary_category is now a string (dynamically generated by LLM),
    not a predefined enum.
    """

    primary_category: str = Field(..., description="Primary classification category (dynamic)")
    secondary_categories: List[str] = Field(
        default_factory=list, description="Secondary classification categories"
    )
    confidence: float = Field(..., ge=0.0, le=1.0, description="Classification confidence score")
    matched_keywords: List[str] = Field(default_factory=list, description="Matched keywords")
    quality_metrics: QualityMetrics = Field(..., description="Quality assessment metrics")
    suggestions: List[str] = Field(default_factory=list, description="Improvement suggestions")
    reasoning: str = Field(default="", description="Classification reasoning from LLM")
    semantic_tags: List[str] = Field(default_factory=list, description="Semantic tags from LLM")
